name: Build and test M-Web-Server docker image
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip_build]')"
    steps:
    - uses: actions/checkout@v2
    - name: Build the M-Web-Server docker image
      run: |
        docker build .
        git clone https://github.com/sumeetchhetri/FrameworkBenchmarks
        cd FrameworkBenchmarks
        git checkout omaster
        ./tfb --mode verify --test ffead-cpp

